brew 'atool'
brew 'bat'
brew 'cmake'
brew 'coreutils'
brew 'diffutils'
brew 'dos2unix'
brew 'findutils'
brew 'fzf'
brew 'git'
brew 'gnu-sed', args: ['with-default-names']
brew 'gnu-tar', args: ['with-default-names']
brew 'gnu-units', args: ['with-default-names']
brew 'gnu-which', args: ['with-default-names']
brew 'gnupg'
brew 'grep', args: ['with-default-names']
brew 'hexyl'
brew 'htop'
brew 'httpie'
brew 'hugo'
brew 'jq'
brew 'just'
brew 'keychain'
brew 'less'
brew 'macvim', args: ['with-override-system-vim']
brew 'make', args: ['with-default-names']
brew 'node'
brew 'openssh'
brew 'openssl', args: ['universal']
brew 'pandoc'
brew 'pkg-config'
brew 'readline'
brew 'ripgrep'
brew 'stow'
brew 'tealdeer'
brew 'tmux'
brew 'tokei'
brew 'tree'
brew 'wget'
brew 'yarn'
brew 'zsh'

# Useful utilities
# brew 'dive'
# brew 'pgcli'
# brew 'shellcheck'
# brew 'tig'
