#!/bin/bash

. ~/bin/bash_colors

if [ -f "${HOME}/bin/git-prompt.sh" ]; then
    . "${HOME}/bin/git-prompt.sh"
fi

# PS1="\n${CYAN}\w ${RESET}\$(__git_ps1 'on ${YELLOW}%s')${RESET}\n% "
PS1="\n${CYAN}\w ${RESET}\$(__git_ps1 'on ${YELLOW}%s')${RESET}\n% "
