#!/bin/bash

. ${HOME}/.bash_colors

GIT_PROMPT_SCRIPT_LOC=${HOME}/bin/git-prompt.sh

PS1="\n"

PS1+="${BLUE}\u"
PS1+="${RESET} "
PS1+="at ${GREEN}\h"
PS1+="${RESET} "
PS1+="in ${YELLOW}\w"
PS1+="${RESET} "
if [ -f $GIT_PROMPT_SCRIPT_LOC ]; then
    source $GIT_PROMPT_SCRIPT_LOC
    PS1+="\$(__git_ps1 '(${VIOLET}%s${RESET})')"
fi
PS1+="\n"
PS1+="% "
