#!/bin/bash

DULL=0
BRIGHT=1

FG_BLACK=30
FG_RED=31
FG_GREEN=32
FG_YELLOW=33
FG_BLUE=34
FG_VIOLET=35
FG_CYAN=36
FG_WHITE=37

FG_NULL=00

BG_BLACK=40
BG_RED=41
BG_GREEN=42
BG_YELLOW=43
BG_BLUE=44
BG_VIOLET=45
BG_CYAN=46
BG_WHITE=47

BG_NULL=00

BEGIN="\[\033["
END="m\]"

dull_color() {
    echo "${BEGIN}${DULL};${1}${END}"
}

bright_color() {
    echo "${BEGIN}${BRIGHT};${1}${END}"
}

BLACK=$(dull_color $FG_BLACK)
RED=$(dull_color $FG_RED)
GREEN=$(dull_color $FG_GREEN)
YELLOW=$(dull_color $FG_YELLOW)
BLUE=$(dull_color $FG_BLUE)
VIOLET=$(dull_color $FG_VIOLET)
CYAN=$(dull_color $FG_CYAN)
WHITE=$(dull_color $FG_WHITE)

BRIGHT_BLACK=$(bright_color $FG_BLACK)
BRIGHT_RED=$(bright_color $FG_RED)
BRIGHT_GREEN=$(bright_color $FG_GREEN)
BRIGHT_YELLOW=$(bright_color $FG_YELLOW)
BRIGHT_BLUE=$(bright_color $FG_BLUE)
BRIGHT_VIOLET=$(bright_color $FG_VIOLET)
BRIGHT_CYAN=$(bright_color $FG_CYAN)
BRIGHT_WHITE=$(bright_color $FG_WHITE)

RESET="${BEGIN}${DULL};${FG_WHITE};${BG_NULL}${END}"

# Alternative to echo which takes a color as its first argument
echoc() {
    if [ $# -eq 2 ]; then
        echo -e "$1$2${RESET}"
    else
        echo $@
    fi
}
