#!/bin/bash

dull_color() {
    echo "${BEGIN}${DULL};${1}${END}"
}

bright_color() {
    echo "${BEGIN}${BRIGHT};${1}${END}"
}

prompt_color_escape() {
    echo "\[$1\]"
}

# Readline uses different characters to escape
readline_color_escape() {
    echo "\001$1\002"
}

colors_init() {
    local DULL=0
    local BRIGHT=1

    local FG_BLACK=30
    local FG_RED=31
    local FG_GREEN=32
    local FG_YELLOW=33
    local FG_BLUE=34
    local FG_VIOLET=35
    local FG_CYAN=36
    local FG_WHITE=37
    local FG_NULL=00

    local BG_BLACK=40
    local BG_RED=41
    local BG_GREEN=42
    local BG_YELLOW=43
    local BG_BLUE=44
    local BG_VIOLET=45
    local BG_CYAN=46
    local BG_WHITE=47
    local BG_NULL=00

    local BEGIN="\033["
    local END="m"

    COLOR_BLACK=$(dull_color $FG_BLACK)
    COLOR_RED=$(dull_color $FG_RED)
    COLOR_GREEN=$(dull_color $FG_GREEN)
    COLOR_YELLOW=$(dull_color $FG_YELLOW)
    COLOR_BLUE=$(dull_color $FG_BLUE)
    COLOR_VIOLET=$(dull_color $FG_VIOLET)
    COLOR_CYAN=$(dull_color $FG_CYAN)
    COLOR_WHITE=$(dull_color $FG_WHITE)

    COLOR_BRIGHT_BLACK=$(bright_color $FG_BLACK)
    COLOR_BRIGHT_RED=$(bright_color $FG_RED)
    COLOR_BRIGHT_GREEN=$(bright_color $FG_GREEN)
    COLOR_BRIGHT_YELLOW=$(bright_color $FG_YELLOW)
    COLOR_BRIGHT_BLUE=$(bright_color $FG_BLUE)
    COLOR_BRIGHT_VIOLET=$(bright_color $FG_VIOLET)
    COLOR_BRIGHT_CYAN=$(bright_color $FG_CYAN)
    COLOR_BRIGHT_WHITE=$(bright_color $FG_WHITE)

    COLOR_RESET="${BEGIN}${DULL};${FG_WHITE};${BG_NULL}${END}"

    COLOR_ESC_BLACK=$(readline_color_escape $COLOR_BLACK)
    COLOR_ESC_RED=$(readline_color_escape $COLOR_RED)
    COLOR_ESC_GREEN=$(readline_color_escape $COLOR_GREEN)
    COLOR_ESC_YELLOW=$(readline_color_escape $COLOR_YELLOW)
    COLOR_ESC_BLUE=$(readline_color_escape $COLOR_BLUE)
    COLOR_ESC_VIOLET=$(readline_color_escape $COLOR_VIOLET)
    COLOR_ESC_CYAN=$(readline_color_escape $COLOR_CYAN)
    COLOR_ESC_WHITE=$(readline_color_escape $COLOR_WHITE)

    COLOR_ESC_BRIGHT_BLACK=$(readline_color_escape $COLOR_BRIGHT_BLACK)
    COLOR_ESC_BRIGHT_RED=$(readline_color_escape $COLOR_BRIGHT_RED)
    COLOR_ESC_BRIGHT_GREEN=$(readline_color_escape $COLOR_BRIGHT_GREEN)
    COLOR_ESC_BRIGHT_YELLOW=$(readline_color_escape $COLOR_BRIGHT_YELLOW)
    COLOR_ESC_BRIGHT_BLUE=$(readline_color_escape $COLOR_BRIGHT_BLUE)
    COLOR_ESC_BRIGHT_VIOLET=$(readline_color_escape $COLOR_BRIGHT_VIOLET)
    COLOR_ESC_BRIGHT_CYAN=$(readline_color_escape $COLOR_BRIGHT_CYAN)
    COLOR_ESC_BRIGHT_WHITE=$(readline_color_escape $COLOR_BRIGHT_WHITE)

    COLOR_ESC_RESET=$(readline_color_escape $COLOR_RESET)
}

colors_init
unset -f dull_color bright_color prompt_color_escape readline_color_escape

echoc() {
    if [ $# -ne 2 ]; then
        echo "Usage: echoc <color> <string>"
        return 1
    fi

    echo -e "$1$2${COLOR_RESET}"
}
