#!/bin/bash

COLOR_BEGIN="\e["
COLOR_END="m"

make_color() {
    echo "${COLOR_BEGIN}${1}${COLOR_END}"
}

prompt_color_escape() {
    echo "\[$1\]"
}

# Readline uses different characters to escape
readline_color_escape() {
    echo "\001$1\002"
}

colors_init() {
    local FG_BLACK=30
    local FG_RED=31
    local FG_GREEN=32
    local FG_YELLOW=33
    local FG_BLUE=34
    local FG_VIOLET=35
    local FG_CYAN=36
    local FG_LIGHT_GRAY=37
    local FG_DARK_GRAY=90
    local FG_LIGHT_RED=91
    local FG_LIGHT_GREEN=92
    local FG_LIGHT_YELLOW=93
    local FG_LIGHT_BLUE=94
    local FG_LIGHT_VIOLET=95
    local FG_LIGHT_CYAN=96
    local FG_WHITE=97

    COLOR_RESET="$(make_color 0)"

    COLOR_BLACK=$(make_color $FG_BLACK)
    COLOR_RED=$(make_color $FG_RED)
    COLOR_GREEN=$(make_color $FG_GREEN)
    COLOR_YELLOW=$(make_color $FG_YELLOW)
    COLOR_BLUE=$(make_color $FG_BLUE)
    COLOR_VIOLET=$(make_color $FG_VIOLET)
    COLOR_CYAN=$(make_color $FG_CYAN)
    COLOR_LIGHT_GRAY=$(make_color $FG_LIGHT_GRAY)
    COLOR_DARK_GRAY=$(make_color $FG_DARK_GRAY)
    COLOR_LIGHT_RED=$(make_color $FG_LIGHT_RED)
    COLOR_LIGHT_GREEN=$(make_color $FG_LIGHT_GREEN)
    COLOR_LIGHT_YELLOW=$(make_color $FG_LIGHT_YELLOW)
    COLOR_LIGHT_BLUE=$(make_color $FG_LIGHT_BLUE)
    COLOR_LIGHT_VIOLET=$(make_color $FG_LIGHT_VIOLET)
    COLOR_LIGHT_CYAN=$(make_color $FG_LIGHT_CYAN)
    COLOR_WHITE=$(make_color $FG_WHITE)

    COLOR_ESC_RESET=$(readline_color_escape $COLOR_RESET)

    COLOR_ESC_BLACK=$(readline_color_escape $COLOR_BLACK)
    COLOR_ESC_RED=$(readline_color_escape $COLOR_RED)
    COLOR_ESC_GREEN=$(readline_color_escape $COLOR_GREEN)
    COLOR_ESC_YELLOW=$(readline_color_escape $COLOR_YELLOW)
    COLOR_ESC_BLUE=$(readline_color_escape $COLOR_BLUE)
    COLOR_ESC_VIOLET=$(readline_color_escape $COLOR_VIOLET)
    COLOR_ESC_CYAN=$(readline_color_escape $COLOR_CYAN)
    COLOR_ESC_LIGHT_GRAY=$(readline_color_escape $COLOR_LIGHT_GRAY)
    COLOR_ESC_DARK_GRAY=$(readline_color_escape $COLOR_DARK_GRAY)
    COLOR_ESC_LIGHT_RED=$(readline_color_escape $COLOR_LIGHT_RED)
    COLOR_ESC_LIGHT_GREEN=$(readline_color_escape $COLOR_LIGHT_GREEN)
    COLOR_ESC_LIGHT_YELLOW=$(readline_color_escape $COLOR_LIGHT_YELLOW)
    COLOR_ESC_LIGHT_BLUE=$(readline_color_escape $COLOR_LIGHT_BLUE)
    COLOR_ESC_LIGHT_VIOLET=$(readline_color_escape $COLOR_LIGHT_VIOLET)
    COLOR_ESC_LIGHT_CYAN=$(readline_color_escape $COLOR_LIGHT_CYAN)
    COLOR_ESC_WHITE=$(readline_color_escape $COLOR_WHITE)
}

colors_init
unset -f make_color prompt_color_escape readline_color_escape COLOR_BEGIN COLOR_END

echoc() {
    if [ $# -ne 2 ]; then
        echo "Usage: echoc <color> <string>"
        return 1
    fi

    echo -e "$1$2${COLOR_RESET}"
}
