#!/bin/bash

# Add a directory to the end of the path if it is not already present
function pathappend() {
    if [ -d "$1" ] && [[ ! "$PATH" =~ (^|:)"${1}"(:|$) ]]; then
        PATH="${PATH:+"$PATH:"}$1";
    fi
}

# Add a directory to the beginning of the path if it is not already present
function pathprepend() {
    if [ -d "$1" ] && [[ ! "$PATH" =~ (^|:)"${1}"(:|$) ]]; then
        PATH="$1${PATH:+":$PATH"}";
    fi
}

function e() {
    # If no vim instance exists, create one
    if [ -z "$(command gvim --serverlist)" ]; then
        command gvim "$@"
        return
    fi

    # Otherwise, open the file in the current instance
    if [ $# -gt 0 ]; then
        command gvim --remote-silent "$@"
    else
        command gvim --remote-silent .
    fi
}

function t() {
    local TMUX_SESSION_NAME="main"

    # If provided with args, pass them through.
    if [[ -n "$@" ]]; then
        tmux "$@"
        return
    fi

    # Attach to existing session, or create one.
    tmux new -A -s "$TMUX_SESSION_NAME"
}
