#!/bin/bash

. ${HOME}/.bash/prompts/git

function set_prompt() {
    PS1="\n"
    PS1+=" "

    if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
        PS1+="[${COLOR_ESC_YELLOW}\h${COLOR_ESC_RESET}] "
    fi

    if [ -n "$PROMPT_FULL_DIR" ]; then
        local PROMPT_DIR_CMD="\w"
    else
        local PROMPT_DIR_CMD="\W"
    fi

    PS1+="${COLOR_ESC_BLUE}${PROMPT_DIR_CMD}${COLOR_ESC_RESET}"
    PS1+="\$(ps1_git)"
    PS1+=" \$${COLOR_ESC_RESET} "
}

set_prompt

function prompt_toggle_dir() {
    if [ -n "$PROMPT_FULL_DIR" ]; then
        unset PROMPT_FULL_DIR
    else
        export PROMPT_FULL_DIR=true
    fi

    set_prompt
}

function prompt_toggle_git() {
    if [ -n "$PROMPT_NO_GIT" ]; then
        unset PROMPT_NO_GIT
    else
        export PROMPT_NO_GIT=true
    fi

    set_prompt
}
