set fish_vi_force_cursor
set fish_cursor_default underscore
set fish_cursor_insert block
set fish_cursor_replace_one underscore
set fish_cursor_replace underscore
set fish_cursor_external line
set fish_cursor_visual block
