#!/bin/bash

. ${HOME}/.bash/colors
. ${HOME}/.bash/prompts/git_prompt

PS1="\n"
PS1+="${BLUE}\u"
PS1+="${RESET} "
PS1+="at ${GREEN}\h${RESET} "
PS1+="in ${YELLOW}\w"
PS1+="${RESET} "
PS1+="\$(__git_ps1 'on ${VIOLET}%s${RESET}')"
PS1+="\n"
PS1+="▶ "
