#!/bin/bash

. ${HOME}/.bash/prompts/elements/git

function set_prompt() {
    local E_BLUE=$(prompt_color_escape $COLOR_BLUE)
    local E_GREEN=$(prompt_color_escape $COLOR_GREEN)
    local E_YELLOW=$(prompt_color_escape $COLOR_YELLOW)
    local E_VIOLET=$(prompt_color_escape $COLOR_VIOLET)
    local E_RESET=$(prompt_color_escape $COLOR_RESET)

    PS1="\n"
    PS1+="${E_BLUE}\u"
    PS1+="${E_RESET} "
    PS1+="at ${E_GREEN}\h${E_RESET} "
    PS1+="in ${E_YELLOW}\w"
    PS1+="${E_RESET} "
    PS1+="\$(__git_ps1 'on ${E_VIOLET}%s${E_RESET}')"
    PS1+="\n"
    PS1+="▶ "
}

set_prompt
