#!/bin/bash
#
# A simple git prompt element which can be added to a bash prompt.
#
# Relies on the git-prompt.sh file which is distributed with git.
#
# Can be configured by setting the following environment variables:
#   export GIT_PS1_SHOWDIRTYSTATE=1
#   export GIT_PS1_SHOWSTASHSTATE=1
#   export GIT_PS1_SHOWUNTRACKEDFILES=1
#   export GIT_PS1_SHOWUPSTREAM="auto"
#

# export GIT_PS1_SHOWDIRTYSTATE=
# export GIT_PS1_SHOWSTASHSTATE=
# export GIT_PS1_SHOWUNTRACKEDFILES=
export GIT_PS1_SHOWUPSTREAM="auto"

case $OSTYPE in
    linux*)
        if [ -f /etc/bash_completion.d/git-prompt ]; then
            GIT_PROMPT_SCRIPT_LOC=/etc/bash_completion.d/git-prompt
        else
            GIT_PROMPT_SCRIPT_LOC=/usr/share/git/git-prompt.sh
        fi
        ;;
    darwin*)
        GIT_PROMPT_SCRIPT_LOC=/usr/local/etc/bash_completion.d/git-prompt.sh
        ;;
esac

if [ -f $GIT_PROMPT_SCRIPT_LOC ]; then
    source $GIT_PROMPT_SCRIPT_LOC
else
    echo "Cannot load ${GIT_PROMPT_SCRIPT_LOC}: Prompt will not contain the current git branch."
fi

# vim: ft=sh
