#!/bin/bash

function ps1_jobs() {
    [ -n "$PROMPT_NO_JOBS" ] && return;

    local stopped=$(jobs -sp | wc -l)

    [ ! $stopped -eq 0 ] && echo -e "${COLOR_ESC_BRIGHT_BLACK}[+${stopped}] ${COLOR_ESC_RESET}"
}
