#!/bin/bash

. ${HOME}/.bash/prompts/elements/git

function set_prompt() {
    local E_BLUE=$(prompt_color_escape $BLUE)
    local E_GREEN=$(prompt_color_escape $GREEN)
    local E_YELLOW=$(prompt_color_escape $YELLOW)
    local E_VIOLET=$(prompt_color_escape $VIOLET)
    local E_RESET=$(prompt_color_escape $RESET)

    PS1="\n ${E_YELLOW}\h${E_RESET}:${E_BLUE}\w${E_RESET}\$(prompt_git) ${E_GREEN}»${E_RESET} "
}

set_prompt
