#!/bin/bash

. ${HOME}/.bash/colors
. ${HOME}/.bash/prompts/elements/git
. ${HOME}/.bash/prompts/elements/virtualenv

E_BLUE=$(color_escape $BLUE)
E_GREEN=$(color_escape $GREEN)
E_VIOLET=$(color_escape $VIOLET)
E_RESET=$(color_escape $RESET)

PS1="\n ${E_BLUE}\w${E_RESET} \$(__git_ps1 '(${E_VIOLET}%s${E_RESET})')\$(prompt_virtualenv) ${E_GREEN}»${E_RESET} "
