#!/bin/bash

. ${HOME}/.bash/prompts/elements/git

function set_prompt() {
    local E_YELLOW=$(prompt_color_escape $YELLOW)
    local E_GREEN=$(prompt_color_escape $GREEN)
    local E_BLUE=$(prompt_color_escape $BLUE)
    local E_VIOLET=$(prompt_color_escape $VIOLET)
    local E_RESET=$(prompt_color_escape $RESET)

    PS1="\n"
    PS1+=" "

    if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
        PS1+="[${E_YELLOW}\h${E_RESET}] "
    fi

    PS1+="${E_BLUE}\w${E_RESET}"
    PS1+="\$(prompt_git)"
    PS1+=" ${E_GREEN}»${E_RESET} "
}

set_prompt
