#!/bin/bash
#
# A virtualenv prompt element which can be added to a bash prompt.
#

function ps1_virtualenv() {
    [[ -n "$VIRTUAL_ENV" ]] && echo -e "${COLOR_ESC_BRIGHT_RED}(venv) ${COLOR_ESC_RESET}"
}

export VIRTUAL_ENV_DISABLE_PROMPT=1

# vim: ft=sh
