user.name = "Jonathan Gilchrist"
user.email = "jonnygilchrist@gmail.com"

ui.default-command = "log"
ui.diff-editor = ":builtin"

[aliases]
s = ["status"]
l = ["log"]
history = ["log", "-r", "::trunk()"]
fetch = ["git", "fetch"]
push = ["git", "push"]

showlast = ["show", "@-"]
showl = ["showlast"]

drafts = ["log", "-r", "draft()"]
rebase-drafts = ["rebase", "-s", "all:roots(draft())", "-d", "trunk()"]

[colors]
"diff removed token" = { underline = false }
"diff added token" = { underline = false }

"timestamp" = { fg = "cyan" }

[revset-aliases]
"draft()" = "mutable() & mine()"

[templates]
log = '''
if(root,
  format_root_commit(self),
  label(if(current_working_copy, "working_copy"),
    concat(
      separate(" ",
        if(!(empty && current_working_copy), format_short_change_id_with_hidden_and_divergent_info(self)),
        if(!mine, format_short_signature(author)),
        tags,
        working_copies,
        if(empty, label("empty", "(empty)")),
        if(description,
          description.first_line(),
          label(if(empty, "empty"), description_placeholder),
        ),
        if(conflict, label("conflict", "conflict")),
        bookmarks,
        if(current_working_copy && !empty, "\n" ++ diff.stat(80)),
      ) ++ "\n",
    ),
  )
)
'''

[template-aliases]
'format_timestamp(timestamp)' = 'timestamp.ago()'

'format_short_signature(signature)' = '''
  coalesce(signature.name(), email_placeholder)'''

'format_root_commit(root)' = '''
separate(" ",
  format_short_change_id(root.change_id()),
  label("root", "root()"),
  root.bookmarks()
) ++ "\n"
'''
