[user]
name = "Jonathan Gilchrist"
email = "jonnygilchrist@gmail.com"

[ui]
default-command = ["log", "-r", "default()"]
diff-editor = ":builtin"
merge-editor = "vim"

[git]
push-bookmark-prefix = "jgilchrist/change/"
private-commits = "private()"
subprocess = true

[merge-tools.vim]
program = "nvim"
merge-tool-edits-conflict-markers = true
merge-args = ["$output"]

[revset-aliases]
"default()" = "default(2)"
"default(n)" = "present(@) | ancestors(immutable_heads().., n) | present(trunk())"

"private()" = "wip()"

"draft()" = "mutable() & mine()"
"experiment()" = "draft() & description(glob-i:\"x:*\")"
"wip()" = "draft() & description(glob-i:\"wip:*\")"

"last()" = "last(20)"
"last(n)" = "ancestors(@, n)"

"stack()" = "stack(@)"
"stack(from)" = "ancestors(reachable(from, mutable()), 2)"

[aliases]
b = ["bookmark"]
s = ["status"]
l = ["log"]
fetch = ["git", "fetch"]
push = ["git", "push"]

history = ["log", "-r", "last()"]

showl = ["show", "@-"]

drafts = ["log", "-r", "draft()"]
rebase-drafts = ["rebase", "-s", "all:roots(draft())", "-d", "trunk()"]

advance = [
    "bookmark",
    "move",
    "--from",
    "heads(::@- & bookmarks())",
    "--to",
    "@-"
]

[colors]
"diff removed token" = { underline = false }
"diff added token" = { underline = false }

[templates]
log = '''
if(root,
  format_root_commit(self),
  label(if(current_working_copy, "working_copy"),
    concat(
      separate(" ",
        if(!(empty && current_working_copy), format_short_change_id_with_hidden_and_divergent_info(self)),
        if(!mine, format_short_signature(author)),
        tags,
        working_copies,
        if(empty, label("empty", "(empty)")),
        if(description,
          description.first_line(),
          label(if(empty, "empty"), description_placeholder),
        ),
        if(conflict, label("conflict", "conflict")),
        bookmarks,
        if(current_working_copy && !empty, "\n" ++ diff.stat(80)),
      ) ++ "\n",
    ),
  )
)
'''

draft_commit_description = '''
concat(
  description,
  surround(
    "\nJJ: This change has the following diffstat:\n", "",
    indent("JJ:   ", diff.stat(72)),
  ),
  "\nJJ: ignore-rest\n",
  diff.git(),
)
'''

[template-aliases]
'format_timestamp(timestamp)' = 'timestamp.ago()'

'format_short_signature(signature)' = '''
  coalesce(signature.name(), email_placeholder)'''
