user.name = "Jonathan Gilchrist"
user.email = "jonnygilchrist@gmail.com"

ui.default-command = "log"

[aliases]
s = ["status"]
l = ["log"]
fetch = ["git", "fetch"]
push = ["git", "push"]

showlast = ["show", "@-"]
showl = ["showlast"]

drafts = ["log", "-r", "draft()"]
rebase-drafts = ["rebase", "-s", "all:roots(drafts())", "-d", "trunk()"]

[revset-aliases]
"draft()" = "mutable() & mine()"
